version: "3"

services:
  dj:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: dj
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./src:/src
    ports:
      - "80:8000"
    env_file:
      - ./src/.env
